services:
  front:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - back
    networks:
      - flashback-network

  back:
    build: ./back
    ports:
      - "8080:8080"
    env_file:
      - ./back/.env
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - flashback-network

  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - "55000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flashback
      POSTGRES_PASSWORD: flashback
      POSTGRES_DB: flashback
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashback"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - flashback-network

networks:
  flashback-network:
    driver: bridge
    external: true
