spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:55000/flashback
spring.datasource.username=flashback
spring.datasource.password=flashback
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
spring.web.resources.add-mappings=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090
keycloak.server.url=http://localhost:8090/realms/flashback
keycloak.realm=flashback
keycloak.admin.client.id=flashback-admin
keycloak.admin.client.secret=x3EQ5lh2Af2z84vXslnaM3KoUTGZGll9
keycloak.admin.client.username=admin
keycloak.admin.client.password=admin

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.username=elastic
spring.elasticsearch.password=iVXpw1tzZD4GkShCfxRe
spring.elasticsearch.uris=localhost:9200
spring.elasticsearch.ssl=77a2b5d807494a6709f360030fa72b5d2c278d23deac599df981206e95a496da

cloud.aws.s3.access-key=123
cloud.aws.s3.secret-key=123
cloud.aws.s3.bucket=flashback-bucket
cloud.aws.s3.region=us-east-1
cloud.aws.s3.image.folder=images

management.endpoints.web.exposure.include=health, metrics, info, prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.diskspace.enabled=true
management.health.db.enabled=true
management.health.ping.enabled=true
management.metrics.enable.all=true